version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8080:80
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    image: bitnami/php-fpm
    env_file:
      - .env
    volumes:
      - ./wordpress_data:/var/www/html
    restart: always
    networks:
      - network
  mariadb:
    container_name: mariadb
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
      - .env

# Stores service data and establishes a connection with the main system
volumes:
  mariadb_data:
    driver:local
    driver_opts:
      type: none
      device: /home/data/mysql
      o: bing

