version: '3'

services:
  nginx: 
    container_name: nginx
    image: nginx42
    build:
      context: ./requirements/nginx
      args:
        - NGINX_HOST_DOMAIN=${DOMAIN_NAME}
    volumes:
      - wordpress:/var/www/html
    ports:
      - 8080:80
    networks:
      - inception
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    image: bitnami/php-fpm
      # build:
      # context: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    restart: on-failure
    networks:
      - inception
  mariadb:
    container_name: mariadb
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env

# Stores service data and establishes a connection with the main system
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/thuynguy/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/thuynguy/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge

