services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env
  nginx: 
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    ports:
      - 443:443
    networks:
      - inception
    restart: on-failure
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    restart: on-failure
    networks:
      - inception

# Stores service data and establishes a connection with the main system
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ./home/thuynguy/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ./home/thuynguy/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge

