version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8080:80
    volumes:
      - wordpress:/var/www/html
    restart: on-failure
    networks:
      - inception
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    image: bitnami/php-fpm
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    restart: on-failure
    networks:
      - inception
    expose:
      - 9000
  mariadb:
    container_name: mariadb
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 3306

# Stores service data and establishes a connection with the main system
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/thuynguy/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/thuynguy/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge

